apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: dozen-backend-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: api.dozen.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: dozen-backend-service
            port:
              number: 8080