apiVersion: apps/v1
kind: Deployment
metadata:
  name: dozen-frontend
  labels:
    app: dozen-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dozen-frontend
  template:
    metadata:
      labels:
        app: dozen-frontend
    spec:
      containers:
      - name: frontend
        image: dozen-frontend:latest
        ports:
        - containerPort: 80
        resources:
          limits:
            cpu: "500m"
            memory: "256Mi"
          requests:
            cpu: "250m"
            memory: "128Mi"